# Generated by Django 4.2.2 on 2023-06-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0005_person_licensenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensenumber',
            name='Person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empApp.person'),
        ),
    ]
